### ISSUE TITLE
Uncorrect download_zenodo log 

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#79] opened 2020-04-02 12:31 UTC
The log I get from `download_zenodo()` is not correct as you can see from screenshot here below:

![image](https://user-images.githubusercontent.com/33662631/78249219-48c30400-74ee-11ea-934c-6b3508a3b2f5.png)

Anybody who has time to find the bug and solve it, is welcome!
Please, noet that files are all and correctly download. Just the log is not correct.

**Comment by florisvdh** [comment] 2020-04-02 12:59
Thanks @damianooldoni !

@hansvancalster recently also [mentioned](https://github.com/inbo/n2khab/pull/29#pullrequestreview-385329319) something like that. The '0 bytes' output comes from `curl::curl_download()`, so I guess either something changed in Zenodo metadata structure or in `curl`. I'll have a look if we can solve it here.

Nice to know that it still works though!

From your output, I guess you're not at the latest version of `inborutils` (total size should be shown in the first, general message).

**Comment by florisvdh** [comment] 2020-04-02 13:28
Hmm, can't reproduce that (in Linux). On second thought, those '0 bytes' won't have to do with changes in Zenodo metadata, this part is entirely created by `curl::curl_download()`. @damianooldoni @hansvancalster  can you install latest master of `inborutils` (`0.1.0.9072`) and try again?

```r
> download_zenodo(doi = "10.5281/zenodo.3637911")
Will download 4 files (total size: 546.6 MiB) from https://doi.org/10.5281/zenodo.3637911 (Occurrence cubes at species level for European countries; version: 20200205)

 [100%] Downloaded 536928205 bytes...
 [100%] Downloaded 1896733 bytes...
 [100%] Downloaded 30845809 bytes...
 [100%] Downloaded 3497791 bytes...

Verifying file integrity...

be_species_cube.csv was downloaded and its integrity verified (md5sum: f3242b773f35fd2f83e167698137caa6)
be_species_info.csv was downloaded and its integrity verified (md5sum: eaba3541a92eb0787ac24399cb573398)
it_species_cube.csv was downloaded and its integrity verified (md5sum: 24a49c734bcfe4bd54e7ef50bae70c18)
it_species_info.csv was downloaded and its integrity verified (md5sum: dbda1e1817527904be1aa85c9a244a13)
```

BTW for multiple large files, you could use `parallel = TRUE`. (but that doesn't show `curl_download()` output)

I propose to use a smaller example from now on (in size), e.g. this one:

```r
download_zenodo(doi = "10.5281/zenodo.3354405")
Will download 10 files (total size: 31.7 MiB) from https://doi.org/10.5281/zenodo.3354405 (GRTSmh_diffres: the raster data source GRTSmaster_habitats converted to 9 hierarchical cell address levels at the corresponding lower resolution; version: GRTSmh_diffres_v1)

 [100%] Downloaded 10270714 bytes...
 [100%] Downloaded 2616242 bytes...
 [100%] Downloaded 614532 bytes...
 [100%] Downloaded 144287 bytes...
 [100%] Downloaded 41149 bytes...
 [100%] Downloaded 10988 bytes...
 [100%] Downloaded 3436 bytes...
 [100%] Downloaded 1584 bytes...
 [100%] Downloaded 1152 bytes...
 [100%] Downloaded 19529728 bytes...

Verifying file integrity...

GRTSmh_diffres.1.tif was downloaded and its integrity verified (md5sum: bf322cf3920cca65d0889b5ffb279c3e)
GRTSmh_diffres.2.tif was downloaded and its integrity verified (md5sum: 5b87f12064f38033aa28bd44726794fa)
GRTSmh_diffres.3.tif was downloaded and its integrity verified (md5sum: c23a0eb6f59116203ace0804aa5983fd)
GRTSmh_diffres.4.tif was downloaded and its integrity verified (md5sum: 50ba461b7fc39d779d58c5a3c3014dea)
GRTSmh_diffres.5.tif was downloaded and its integrity verified (md5sum: 353b2ff2d6c74586375226a4d53a4e26)
GRTSmh_diffres.6.tif was downloaded and its integrity verified (md5sum: 8e5ae8bc94daeda644c7b9d51a6c6bf0)
GRTSmh_diffres.7.tif was downloaded and its integrity verified (md5sum: 41b2d931b81d3b51366837f5a0224f53)
GRTSmh_diffres.8.tif was downloaded and its integrity verified (md5sum: 1d9ebd285cbaf2b1aece89597477236f)
GRTSmh_diffres.9.tif was downloaded and its integrity verified (md5sum: 561ff07eae0b4dfcb3a3ee01975ff82a)
GRTSmh_diffres.gpkg was downloaded and its integrity verified (md5sum: 66d688329aa4063e5a6747c0c097097a)
```

**Comment by florisvdh** [comment] 2020-04-02 13:52
I bet your problem will persist after upgrading `inborutils`.

@damianooldoni can you provide your output of:

```r
library(curl)
file_urls <- c("https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.1.tif", 
          "https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.2.tif")
destfiles <- c("./GRTSmh_diffres.1.tif", "./GRTSmh_diffres.2.tif")
curl_download(file_urls[2], destfiles[2], quiet = FALSE)
mapply(curl_download,
       file_urls,
       destfiles,
       MoreArgs = list(quiet = FALSE))
```

**Comment by damianooldoni** [comment] 2020-04-02 16:37
I updated `inborutils`, but indeed it didn't solved the problem. 
@florisvdh, this is the output I get:
```r
> library(inborutils)
> curl_download(file_urls[2], destfiles[2], quiet = FALSE)
 [0%] Downloaded 0 bytes...
> mapply(curl_download,
+        file_urls,
+        destfiles,
+        MoreArgs = list(quiet = FALSE))
 [1073741824%] Downloaded 0 bytes....
 [0%] Downloaded 0 bytes...
    https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.1.tif 
"C:\\Users\\damiano_oldoni\\Documents\\INBO\\repositories\\pipeline\\GRTSmh_diffres.1.tif" 
    https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.2.tif 
"C:\\Users\\damiano_oldoni\\Documents\\INBO\\repositories\\pipeline\\GRTSmh_diffres.2.tif" 
```

**Comment by florisvdh** [comment] 2020-04-02 19:23
OK thank you @damianooldoni . The simple part:

```r
> curl_download(file_urls[2], destfiles[2], quiet = FALSE)
 [0%] Downloaded 0 bytes...
```

... demonstrates that the problem is with `curl::curl_download()` or further upstream (it calls 
the `curl` tool which uses `libcurl`). The latest CRAN-release of the `curl` package dates from 2 Dec 2019. Maybe something changed there for Windows users, potentially because of an update in the `curl` tool or in `libcurl` (see [curl/curl](https://github.com/curl/curl)).

@damianooldoni  I suggest you submit an issue with your output & session info of the simple `curl_download(quiet = FALSE)` example at https://github.com/jeroen/curl where the R-package lives, to find out whether it can be resolved either in the R-package, or upstream (`libcurl`). I don't think there's an issue for that already. You can mention it was not a problem in some 'earlier' day (at least @hansvancalster can testify that the message worked in Windows, probably half a year or so ago).

In Linux (session info below) it is not a problem:

```r
> library(curl)
> file_urls <- c("https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.1.tif", 
+                "https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.2.tif")
> destfiles <- c("./GRTSmh_diffres.1.tif", "./GRTSmh_diffres.2.tif")
> curl_download(file_urls[2], destfiles[2], quiet = FALSE)
 [100%] Downloaded 2616242 bytes...
```

<details> <summary><strong>sessioninfo::session_info()</strong></summary>

```r
─ Session info ─────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Linux Mint 18.1             
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  nl_BE.UTF-8                 
 ctype    nl_BE.UTF-8                 
 tz       Europe/Brussels             
 date     2020-04-02                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 curl        * 4.3     2019-12-02 [1] CRAN (R 3.6.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 drat          0.1.5   2019-03-28 [1] CRAN (R 3.6.0)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 fs            1.3.2   2020-03-05 [1] CRAN (R 3.6.3)
 glue          1.3.2   2020-03-12 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 packrat       0.5.0   2018-11-14 [1] CRAN (R 3.6.0)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.3)
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.2)
 Rcpp          1.0.4   2020-03-17 [1] CRAN (R 3.6.3)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)

[1] /home/floris/lib/R/library
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```
</details>

**Comment by florisvdh** [comment] 2020-04-02 19:26
Considering this is an upstream bug which does not harm core functionality, I think it's best to close the issue here.

**Closed as completed by florisvdh** 2020-04-02 19:26 UTC
Labels: bug
